fn_output_prefix = "eval_spacing_"
fn_result_dir = "results/eval_tr/"
fn_figure_dir = "figures/eval_tr/"
dataset_path = "data/TASCAR_IRs/measured_irs_tr.npz"
mode = "tr"
spacing_fixpos = [2.5, 5.0, 10.0, 15.0, 25.0]  # spacing of the reference points, centimeters
interpolation_methods = ["direct", "nn", "dtw"]  # Methods to test
step_patterns = ["symmetricP2"]  # Allowed step patterns for DTW
ir_ds_factor = 6  # downsampling factor for IRs
ir_range = [0, 64]  # taps of the IR to consider in analysis (was: range(0, 64))
plot_sm_limits = [-40, 8]  # dB
plot_mag_limits = [-30, 0]  # dB
plot_nfft = 512
export_figures = true
export_results = true