fn_output_prefix = "eval_steppattern_tr_"
fn_result_dir = "results/metrics/eval_steppattern_tr/"
fn_figure_dir = "results/figures/eval_steppattern_tr/"
dataset_path = "data/TASCAR_IRs/measured_irs_tr.npz"
mode = "tr"
spacing_fixpos = [15.0]  # spacing of the reference points, centimeters
interpolation_methods = ["nn", "direct", "dtw"]  # Methods to test
dewarping_interpolator = "cs"  # Interpolator to extract values at integer positions after dewarping
step_patterns = [
    "symmetric1",
    "symmetric2",
    "symmetricP0",
    "symmetricP05",
    "symmetricP1",
    "symmetricP2",
]  # Allowed step patterns for DTW
ir_ds_factor = 1  # downsampling factor for IRs
ir_range = [0, 64]  # taps of the IR to consider in analysis (was: range(0, 64))
plot_sm_limits = [-40, 8]  # dB
plot_mag_limits = [-30, 0]  # dB
plot_nfft = 512
export_figures = true
export_results = true